<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Seeder class for the comments table.
 * Generated by Laravel DB Craft.
 * Generated on: 2026-05-30 13:04:56
 */
class CommentsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key checks
        DB::statement('SET CONSTRAINTS ALL DEFERRED;');
        
        // Truncate the table
        DB::table('comments')->truncate();
        
        // Insert data in chunks
        DB::table('comments')->insert([
            [
                'id' => 1,
                'user_id' => 1,
                'title_id' => 10,
                'content' => 'ehehehth',
                'created_at' => '2026-05-06 09:52:31',
                'updated_at' => '2026-05-06 09:52:31',
            ],
            [
                'id' => 2,
                'user_id' => 1,
                'title_id' => 7,
                'content' => 'tehtehfd2h4t2',
                'created_at' => '2026-05-06 09:52:47',
                'updated_at' => '2026-05-06 09:52:47',
            ],
            [
                'id' => 3,
                'user_id' => 1,
                'title_id' => 9,
                'content' => 'tj6j3ethdfh',
                'created_at' => '2026-05-06 09:52:54',
                'updated_at' => '2026-05-06 09:52:54',
            ],
            [
                'id' => 4,
                'user_id' => 1,
                'title_id' => 10,
                'content' => 'tejtjej',
                'created_at' => '2026-05-06 13:45:59',
                'updated_at' => '2026-05-06 13:45:59',
            ],
            [
                'id' => 5,
                'user_id' => 1,
                'title_id' => 10,
                'content' => 'alert("gghghhghg")',
                'created_at' => '2026-05-08 11:23:38',
                'updated_at' => '2026-05-08 11:23:38',
            ],
            [
                'id' => 6,
                'user_id' => 1,
                'title_id' => 10,
                'content' => 'alert("gghghhghg")',
                'created_at' => '2026-05-08 11:23:39',
                'updated_at' => '2026-05-08 11:23:39',
            ],
            [
                'id' => 7,
                'user_id' => 3,
                'title_id' => 3,
                'content' => 'Душевная манга, графита маму ебал',
                'created_at' => '2026-05-08 11:53:50',
                'updated_at' => '2026-05-08 11:53:50',
            ],
            [
                'id' => 8,
                'user_id' => 4,
                'title_id' => 10,
                'content' => 833535,
                'created_at' => '2026-05-11 07:23:11',
                'updated_at' => '2026-05-11 07:23:11',
            ],
            [
                'id' => 9,
                'user_id' => 4,
                'title_id' => 10,
                'content' => 111,
                'created_at' => '2026-05-11 07:26:31',
                'updated_at' => '2026-05-11 07:26:31',
            ],
            [
                'id' => 10,
                'user_id' => 4,
                'title_id' => 10,
                'content' => 111,
                'created_at' => '2026-05-11 07:26:31',
                'updated_at' => '2026-05-11 07:26:31',
            ],
            [
                'id' => 11,
                'user_id' => 4,
                'title_id' => 10,
                'content' => 111,
                'created_at' => '2026-05-11 07:26:31',
                'updated_at' => '2026-05-11 07:26:31',
            ],
        ]);
        
        // Re-enable foreign key checks
        DB::statement('SET CONSTRAINTS ALL IMMEDIATE;');
    }
}