<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Seeder class for the favorites table.
 * Generated by Laravel DB Craft.
 * Generated on: 2026-05-30 13:04:56
 */
class FavoritesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key checks
        DB::statement('SET CONSTRAINTS ALL DEFERRED;');
        
        // Truncate the table
        DB::table('favorites')->truncate();
        
        // Insert data in chunks
        DB::table('favorites')->insert([
            [
                'id' => 4,
                'user_id' => 3,
                'title_id' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 5,
                'user_id' => 4,
                'title_id' => 10,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 6,
                'user_id' => 1,
                'title_id' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
        ]);
        
        // Re-enable foreign key checks
        DB::statement('SET CONSTRAINTS ALL IMMEDIATE;');
    }
}