<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Seeder class for the sessions table.
 * Generated by Laravel DB Craft.
 * Generated on: 2026-05-30 13:04:56
 */
class SessionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key checks
        DB::statement('SET CONSTRAINTS ALL DEFERRED;');
        
        // Truncate the table
        DB::table('sessions')->truncate();
        
        // Insert data in chunks
        DB::table('sessions')->insert([
            [
                'id' => 'ffNnO6CyStfjcgXk6fCL9sjLG96P0isR8GppL3fm',
                'user_id' => 1,
                'ip_address' => '10.99.162.220',
                'user_agent' => 'Mozilla/5.0 (iPhone; CPU iPhone OS 18_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.5 Mobile/15E148 Safari/604.1',
                'payload' => 'eyJfdG9rZW4iOiJnVUE1RElabHZaWjYwQnJ3bVpFN3JDUkZQelpVc3ZBdUNUSk5rUGg1IiwiX3ByZXZpb3VzIjp7InVybCI6Imh0dHA6XC9cLzEwLjk5LjE2Mi4yMjA6ODAwMFwvdGl0bGVcL21hZGUtaW4tYWJ5c3MiLCJyb3V0ZSI6InRpdGxlcy5zaG93In0sIl9mbGFzaCI6eyJvbGQiOltdLCJuZXciOltdfSwibG9naW5fd2ViXzU5YmEzNmFkZGMyYjJmOTQwMTU4MGYwMTRjN2Y1OGVhNGUzMDk4OWQiOjF9',
                'last_activity' => 1778679048,
            ],
            [
                'id' => 'lAt0tC2Bhan2alpqVkow0ByF1O6JwgDPaNGtRYTO',
                'user_id' => null,
                'ip_address' => '10.99.162.220',
                'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36',
                'payload' => 'eyJfdG9rZW4iOiJTZjBUUmRuZ2tuV0pnR2lLOThvUjlTajNFdVQ4dVpWM20zZ0NQMFlsIiwiX3ByZXZpb3VzIjp7InVybCI6Imh0dHA6XC9cLzEwLjk5LjE2Mi4yMjA6ODAwMCIsInJvdXRlIjoiaG9tZSJ9LCJfZmxhc2giOnsib2xkIjpbXSwibmV3IjpbXX19',
                'last_activity' => 1779112389,
            ],
        ]);
        
        // Re-enable foreign key checks
        DB::statement('SET CONSTRAINTS ALL IMMEDIATE;');
    }
}