<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Seeder class for the tags table.
 * Generated by Laravel DB Craft.
 * Generated on: 2026-05-30 13:04:56
 */
class TagsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key checks
        DB::statement('SET CONSTRAINTS ALL DEFERRED;');
        
        // Truncate the table
        DB::table('tags')->truncate();
        
        // Insert data in chunks
        DB::table('tags')->insert([
            [
                'id' => 1,
                'name' => 'приключения',
                'created_at' => '2026-05-06 09:17:32',
                'updated_at' => '2026-05-06 09:17:32',
            ],
            [
                'id' => 2,
                'name' => 'фантастика',
                'created_at' => '2026-05-06 09:17:32',
                'updated_at' => '2026-05-06 09:17:32',
            ],
            [
                'id' => 3,
                'name' => 'фэнтези',
                'created_at' => '2026-05-06 09:17:32',
                'updated_at' => '2026-05-06 09:17:32',
            ],
            [
                'id' => 4,
                'name' => 'драма',
                'created_at' => '2026-05-06 09:17:32',
                'updated_at' => '2026-05-06 09:17:32',
            ],
            [
                'id' => 5,
                'name' => 'трагедия',
                'created_at' => '2026-05-06 09:17:32',
                'updated_at' => '2026-05-06 09:17:32',
            ],
            [
                'id' => 6,
                'name' => 'сэйнен',
                'created_at' => '2026-05-06 09:17:32',
                'updated_at' => '2026-05-06 09:17:32',
            ],
            [
                'id' => 7,
                'name' => 'сёнен',
                'created_at' => '2026-05-06 09:17:32',
                'updated_at' => '2026-05-06 09:17:32',
            ],
            [
                'id' => 8,
                'name' => 'экшен',
                'created_at' => '2026-05-06 09:17:32',
                'updated_at' => '2026-05-06 09:17:32',
            ],
            [
                'id' => 9,
                'name' => 'романтика',
                'created_at' => '2026-05-06 09:17:32',
                'updated_at' => '2026-05-06 09:17:32',
            ],
            [
                'id' => 10,
                'name' => 'ужасы',
                'created_at' => '2026-05-06 09:17:32',
                'updated_at' => '2026-05-06 09:17:32',
            ],
            [
                'id' => 11,
                'name' => 'сэйнэн',
                'created_at' => '2026-05-06 09:17:32',
                'updated_at' => '2026-05-06 09:17:32',
            ],
            [
                'id' => 12,
                'name' => 'боевик',
                'created_at' => '2026-05-06 09:17:32',
                'updated_at' => '2026-05-06 09:17:32',
            ],
            [
                'id' => 13,
                'name' => 'мистика',
                'created_at' => '2026-05-06 09:17:32',
                'updated_at' => '2026-05-06 09:17:32',
            ],
            [
                'id' => 14,
                'name' => 'меха',
                'created_at' => '2026-05-06 09:17:32',
                'updated_at' => '2026-05-06 09:17:32',
            ],
            [
                'id' => 15,
                'name' => 'сёнэн',
                'created_at' => '2026-05-06 09:17:32',
                'updated_at' => '2026-05-06 09:17:32',
            ],
            [
                'id' => 16,
                'name' => 'комедия',
                'created_at' => '2026-05-06 09:17:32',
                'updated_at' => '2026-05-06 09:17:32',
            ],
            [
                'id' => 17,
                'name' => 'психология',
                'created_at' => '2026-05-06 09:17:32',
                'updated_at' => '2026-05-06 09:17:32',
            ],
            [
                'id' => 18,
                'name' => 'повседневность',
                'created_at' => '2026-05-06 09:17:32',
                'updated_at' => '2026-05-06 09:17:32',
            ],
            [
                'id' => 19,
                'name' => 'эротика',
                'created_at' => '2026-05-06 09:17:32',
                'updated_at' => '2026-05-06 09:17:32',
            ],
            [
                'id' => 20,
                'name' => 'военное',
                'created_at' => '2026-05-06 09:17:32',
                'updated_at' => '2026-05-06 09:17:32',
            ],
            [
                'id' => 21,
                'name' => 'навыки / способности',
                'created_at' => '2026-05-06 09:17:32',
                'updated_at' => '2026-05-06 09:17:32',
            ],
            [
                'id' => 22,
                'name' => 'гарем',
                'created_at' => '2026-05-06 09:17:32',
                'updated_at' => '2026-05-06 09:17:32',
            ],
            [
                'id' => 23,
                'name' => 'исэкай',
                'created_at' => '2026-05-06 09:17:32',
                'updated_at' => '2026-05-06 09:17:32',
            ],
            [
                'id' => 24,
                'name' => 'боевые искусства',
                'created_at' => '2026-05-06 09:17:32',
                'updated_at' => '2026-05-06 09:17:32',
            ],
            [
                'id' => 25,
                'name' => 'триллер',
                'created_at' => '2026-05-06 09:17:32',
                'updated_at' => '2026-05-06 09:17:32',
            ],
            [
                'id' => 26,
                'name' => 'дзёсэй',
                'created_at' => '2026-05-06 09:17:32',
                'updated_at' => '2026-05-06 09:17:32',
            ],
        ]);
        
        // Re-enable foreign key checks
        DB::statement('SET CONSTRAINTS ALL IMMEDIATE;');
    }
}