<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Seeder class for the title_tag table.
 * Generated by Laravel DB Craft.
 * Generated on: 2026-05-30 13:04:56
 */
class TitleTagTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key checks
        DB::statement('SET CONSTRAINTS ALL DEFERRED;');
        
        // Truncate the table
        DB::table('title_tag')->truncate();
        
        // Insert data in chunks
        DB::table('title_tag')->insert([
            [
                'id' => 1,
                'title_id' => 1,
                'tag_id' => 7,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 2,
                'title_id' => 1,
                'tag_id' => 8,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 3,
                'title_id' => 1,
                'tag_id' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 4,
                'title_id' => 1,
                'tag_id' => 9,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 5,
                'title_id' => 2,
                'tag_id' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 6,
                'title_id' => 2,
                'tag_id' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 7,
                'title_id' => 2,
                'tag_id' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 8,
                'title_id' => 2,
                'tag_id' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 9,
                'title_id' => 2,
                'tag_id' => 5,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 10,
                'title_id' => 2,
                'tag_id' => 6,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 11,
                'title_id' => 3,
                'tag_id' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 12,
                'title_id' => 3,
                'tag_id' => 10,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 13,
                'title_id' => 3,
                'tag_id' => 11,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 14,
                'title_id' => 3,
                'tag_id' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 15,
                'title_id' => 3,
                'tag_id' => 12,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 16,
                'title_id' => 3,
                'tag_id' => 13,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 17,
                'title_id' => 3,
                'tag_id' => 5,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 18,
                'title_id' => 4,
                'tag_id' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 19,
                'title_id' => 4,
                'tag_id' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 20,
                'title_id' => 4,
                'tag_id' => 14,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 21,
                'title_id' => 4,
                'tag_id' => 15,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 22,
                'title_id' => 5,
                'tag_id' => 11,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 23,
                'title_id' => 5,
                'tag_id' => 16,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 24,
                'title_id' => 5,
                'tag_id' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 25,
                'title_id' => 5,
                'tag_id' => 17,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 26,
                'title_id' => 5,
                'tag_id' => 18,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 27,
                'title_id' => 5,
                'tag_id' => 19,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 28,
                'title_id' => 6,
                'tag_id' => 12,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 29,
                'title_id' => 6,
                'tag_id' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 30,
                'title_id' => 6,
                'tag_id' => 15,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 31,
                'title_id' => 6,
                'tag_id' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 32,
                'title_id' => 6,
                'tag_id' => 20,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 33,
                'title_id' => 6,
                'tag_id' => 21,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 34,
                'title_id' => 7,
                'tag_id' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 35,
                'title_id' => 7,
                'tag_id' => 12,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 36,
                'title_id' => 7,
                'tag_id' => 9,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 37,
                'title_id' => 7,
                'tag_id' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 38,
                'title_id' => 7,
                'tag_id' => 22,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 39,
                'title_id' => 7,
                'tag_id' => 23,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 40,
                'title_id' => 7,
                'tag_id' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 41,
                'title_id' => 7,
                'tag_id' => 11,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 42,
                'title_id' => 8,
                'tag_id' => 15,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 43,
                'title_id' => 8,
                'tag_id' => 12,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 44,
                'title_id' => 8,
                'tag_id' => 16,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 45,
                'title_id' => 9,
                'tag_id' => 25,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 46,
                'title_id' => 9,
                'tag_id' => 13,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 47,
                'title_id' => 9,
                'tag_id' => 10,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 48,
                'title_id' => 9,
                'tag_id' => 26,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 49,
                'title_id' => 10,
                'tag_id' => 12,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 50,
                'title_id' => 10,
                'tag_id' => 24,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 51,
                'title_id' => 10,
                'tag_id' => 15,
                'created_at' => null,
                'updated_at' => null,
            ],
        ]);
        
        // Re-enable foreign key checks
        DB::statement('SET CONSTRAINTS ALL IMMEDIATE;');
    }
}