<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Seeder class for the titles table.
 * Generated by Laravel DB Craft.
 * Generated on: 2026-05-30 13:04:56
 */
class TitlesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key checks
        DB::statement('SET CONSTRAINTS ALL DEFERRED;');
        
        // Truncate the table
        DB::table('titles')->truncate();
        
        // Insert data in chunks
        DB::table('titles')->insert([
            [
                'id' => 1,
                'title' => 'InuYasha Manga',
                'slug' => 'inuyasha-manga',
                'description' => null,
                'cover_image' => '/storage/covers/inuyasha-manga/title.jpg',
                'created_at' => '2026-05-06 09:17:32',
                'updated_at' => '2026-05-06 09:17:32',
            ],
            [
                'id' => 2,
                'title' => 'Made in Abyss',
                'slug' => 'made-in-abyss',
                'description' => null,
                'cover_image' => '/storage/covers/made-in-abyss/title.jpg',
                'created_at' => '2026-05-06 09:17:40',
                'updated_at' => '2026-05-06 09:17:40',
            ],
            [
                'id' => 3,
                'title' => 'Miura Kentarou - Berserk',
                'slug' => 'miura-kentarou-berserk',
                'description' => null,
                'cover_image' => '/storage/covers/miura-kentarou-berserk/title.jpg',
                'created_at' => '2026-05-06 09:17:42',
                'updated_at' => '2026-05-06 09:17:42',
            ],
            [
                'id' => 4,
                'title' => 'Neon Genesis Evangelion',
                'slug' => 'neon-genesis-evangelion',
                'description' => null,
                'cover_image' => '/storage/covers/neon-genesis-evangelion/title.jpg',
                'created_at' => '2026-05-06 09:17:44',
                'updated_at' => '2026-05-06 09:17:44',
            ],
            [
                'id' => 5,
                'title' => 'Oyasumi Punpun (1-147) (complete)',
                'slug' => 'oyasumi-punpun-1-147-complete',
                'description' => null,
                'cover_image' => '/storage/covers/oyasumi-punpun-1-147-complete/title.jpg',
                'created_at' => '2026-05-06 09:17:47',
                'updated_at' => '2026-05-06 09:17:47',
            ],
            [
                'id' => 6,
                'title' => 'Solo Leveling',
                'slug' => 'solo-leveling',
                'description' => null,
                'cover_image' => '/storage/covers/solo-leveling/title.jpeg',
                'created_at' => '2026-05-06 09:17:47',
                'updated_at' => '2026-05-06 09:17:47',
            ],
            [
                'id' => 7,
                'title' => 'Tate no Yuusha no Nariagari',
                'slug' => 'tate-no-yuusha-no-nariagari',
                'description' => null,
                'cover_image' => '/storage/covers/tate-no-yuusha-no-nariagari/title.jpg',
                'created_at' => '2026-05-06 09:17:48',
                'updated_at' => '2026-05-06 09:17:48',
            ],
            [
                'id' => 8,
                'title' => 'Кайдзю №8',
                'slug' => 'kaidziu-8',
                'description' => null,
                'cover_image' => '/storage/covers/kaidziu-8/title.jpg',
                'created_at' => '2026-05-06 09:17:50',
                'updated_at' => '2026-05-06 09:17:50',
            ],
            [
                'id' => 9,
                'title' => 'Магазинчик ужасов',
                'slug' => 'magazincik-uzasov',
                'description' => null,
                'cover_image' => '/storage/covers/magazincik-uzasov/title.jpg',
                'created_at' => '2026-05-06 09:17:52',
                'updated_at' => '2026-05-06 09:17:52',
            ],
            [
                'id' => 10,
                'title' => 'боец баки на русском',
                'slug' => 'boec-baki-na-russkom',
                'description' => null,
                'cover_image' => '/storage/covers/boec-baki-na-russkom/title.jpg',
                'created_at' => '2026-05-06 09:17:54',
                'updated_at' => '2026-05-06 09:17:54',
            ],
        ]);
        
        // Re-enable foreign key checks
        DB::statement('SET CONSTRAINTS ALL IMMEDIATE;');
    }
}