<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Seeder class for the users table.
 * Generated by Laravel DB Craft.
 * Generated on: 2026-05-30 13:04:56
 */
class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key checks
        DB::statement('SET CONSTRAINTS ALL DEFERRED;');
        
        // Truncate the table
        DB::table('users')->truncate();
        
        // Insert data in chunks
        DB::table('users')->insert([
            [
                'id' => 1,
                'name' => 'fff',
                'email' => 'mail@mail.ru',
                'email_verified_at' => null,
                'password' => '$2y$12$tYAlSXZtgfncewpJXJ3haOi62A8.r9nMrCWqBnz56PxU.tauy9CPS',
                'remember_token' => null,
                'created_at' => '2026-05-06 09:52:21',
                'updated_at' => '2026-05-06 09:52:21',
            ],
            [
                'id' => 2,
                'name' => 'кикркр',
                'email' => 'ccountant@tourist-club.ru',
                'email_verified_at' => null,
                'password' => '$2y$12$gXDO0puWD/MiTvSMH5X8q.BzFGk0bB6AXlBpj25KlzQyaXN/Mf/8m',
                'remember_token' => null,
                'created_at' => '2026-05-06 13:51:08',
                'updated_at' => '2026-05-06 13:51:08',
            ],
            [
                'id' => 3,
                'name' => 'Roman',
                'email' => 'ostriynskiy@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$ns5xoaqld1sEuZKHYqYIuuGJob4EhbbLgOjfR2eSuDWusek8frWDO',
                'remember_token' => null,
                'created_at' => '2026-05-08 11:53:11',
                'updated_at' => '2026-05-08 11:53:11',
            ],
            [
                'id' => 4,
                'name' => 'gfghfhffh',
                'email' => 'ekaterina@mail.ru',
                'email_verified_at' => null,
                'password' => '$2y$12$V7LwLHfJzINjKdH.VKPqvOUCi7qoVQ.vYODX41ZJ28Uyt9XdPrx/G',
                'remember_token' => null,
                'created_at' => '2026-05-11 07:21:28',
                'updated_at' => '2026-05-11 07:21:28',
            ],
        ]);
        
        // Re-enable foreign key checks
        DB::statement('SET CONSTRAINTS ALL IMMEDIATE;');
    }
}